[workspace]
members = [
    "btmesh-bearer",
    "btmesh-common",
    "btmesh-driver",
    "btmesh-models",
    "btmesh-pdu",
    "btmesh-macro",
]

resolver = "2"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "36a1f203648dcb402727ea3eb5d30cf1f6993795" }
