[package]
name = "btmesh-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btmesh-common = { path = "../btmesh-common" }
btmesh-pdu = { path = "../btmesh-pdu" }
heapless = "0.7.13"
hash32 = "0.2.1"
hash32-derive = "0.1.1"
uluru = "3.0.0"
serde = "1.0"

