[workspace]
# none, due to architecture target

[package]
name = "btmesh-nrf-softdevice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btmesh-pdu = { path = "../btmesh-pdu" }
btmesh-bearer = { path = "../btmesh-bearer" }
btmesh-driver = { path = "../btmesh-driver" }
heapless = "=0.7.13"
atomic-polyfill = "0.1.8"

embassy = { version = "0.1.0", default-features = false, features = ["executor-agnostic", "nightly"] }
nrf-softdevice = { version = "0.1.0", features = ["ble-peripheral", "ble-gatt-server"], optional=true }
nrf-softdevice-s113 = { version = "0.1.0", optional=true }
nrf-softdevice-s140 = { version = "0.1.0", optional=true }

[features]
"nrf52840" = [
    "nrf-softdevice/nrf52840",
    "nrf-softdevice/ble-central",
    "nrf-softdevice/s140",
    "nrf-softdevice-s140",
]

"nrf52833" = [
    "nrf-softdevice/nrf52833",
    "nrf-softdevice-s113",
]

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "36a1f203648dcb402727ea3eb5d30cf1f6993795" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice/", rev = "a5026485151138112b522a27c4a340614d7a7512" }
nrf-softdevice-s140 = { git = "https://github.com/embassy-rs/nrf-softdevice/", rev = "a5026485151138112b522a27c4a340614d7a7512" }
nrf-softdevice-macro = { git = "https://github.com/embassy-rs/nrf-softdevice/", rev = "a5026485151138112b522a27c4a340614d7a7512" }